# Generated by Django 4.2.7 on 2025-10-16 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=14)),
                ('level', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('DEBUG', 'Debug')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Log de Análise',
                'verbose_name_plural': 'Logs de Análise',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CNPJData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('founded_date', models.DateField()),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('main_activity', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dados do CNPJ',
                'verbose_name_plural': 'Dados dos CNPJs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(help_text='Score de 0 a 100')),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('ATENCAO', 'Atenção'), ('REPROVADO', 'Reprovado')], max_length=10)),
                ('risk_level', models.CharField(help_text='Baixo, Médio, Alto', max_length=20)),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_time', models.FloatField(help_text='Tempo de processamento em segundos')),
                ('cnpj_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analysis.cnpjdata')),
            ],
            options={
                'verbose_name': 'Resultado da Análise',
                'verbose_name_plural': 'Resultados das Análises',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(max_length=100)),
                ('criteria_description', models.TextField()),
                ('score', models.IntegerField(help_text='Score de 0 a 100 para este critério')),
                ('weight', models.FloatField(help_text='Peso do critério na análise geral')),
                ('passed', models.BooleanField()),
                ('details', models.JSONField(default=dict, help_text='Detalhes específicos do critério')),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='analysis.analysisresult')),
            ],
            options={
                'verbose_name': 'Critério da Análise',
                'verbose_name_plural': 'Critérios das Análises',
                'ordering': ['-weight'],
            },
        ),
    ]
